#!/usr/bin/env bash
# tools/debug-qemu.sh — Launch NEOMACH under QEMU and attach GDB
#
# This script starts QEMU with:
#   -s   : GDB stub listening on TCP port 1234
#   -S   : Pause at the very first instruction and wait for GDB to connect
#
# Then it launches GDB, loads kernel symbols, and connects to the stub.
#
# Usage:
#   Terminal 1:  ./tools/debug-qemu.sh   (launches both QEMU and GDB)
#
#   Or, for split-terminal debugging:
#   Terminal 1:  ./tools/run-qemu.sh      (run QEMU with -s but without -S)
#   Terminal 2:  ./tools/debug-qemu.sh --gdb-only
#
# Options:
#   --no-build     Skip the CMake build step
#   --no-kvm       Force TCG software emulation
#   --gdb-only     Only launch GDB (assumes QEMU is already running)

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BUILD_DIR="${REPO_ROOT}/build"
KERNEL_IMG="${BUILD_DIR}/kernel/neomach.elf"

DO_BUILD=1
FORCE_TCG=0
GDB_ONLY=0

for arg in "$@"; do
    case "$arg" in
        --no-build) DO_BUILD=0 ;;
        --no-kvm)   FORCE_TCG=1 ;;
        --gdb-only) GDB_ONLY=1 ;;
        *) echo "Unknown argument: $arg" >&2; exit 1 ;;
    esac
done

# ---------------------------------------------------------------------------
# Build (unless skipped or GDB-only)
# ---------------------------------------------------------------------------
if [[ $DO_BUILD -eq 1 ]] && [[ $GDB_ONLY -eq 0 ]]; then
    echo "[debug-qemu] Configuring CMake build in ${BUILD_DIR} ..."
    cmake -S "${REPO_ROOT}" -B "${BUILD_DIR}" -DCMAKE_BUILD_TYPE=Debug \
          -DNEOMACH_BOOT_TESTS=ON --no-warn-unused-cli -q

    echo "[debug-qemu] Building NEOMACH kernel ..."
    cmake --build "${BUILD_DIR}" --target neomach.elf
fi

if [[ ! -f "${KERNEL_IMG}" ]]; then
    echo "[debug-qemu] ERROR: kernel image not found at ${KERNEL_IMG}" >&2
    exit 1
fi

# ---------------------------------------------------------------------------
# Start QEMU in the background (unless --gdb-only)
# ---------------------------------------------------------------------------
if [[ $GDB_ONLY -eq 0 ]]; then
    ACCEL_FLAGS=()
    if [[ $FORCE_TCG -eq 0 ]] && [[ -w /dev/kvm ]]; then
        ACCEL_FLAGS=(-accel kvm -cpu host)
    else
        ACCEL_FLAGS=(-accel tcg -cpu qemu64)
    fi

    echo "[debug-qemu] Starting QEMU (paused, waiting for GDB) ..."
    qemu-system-x86_64 \
        -machine q35 \
        "${ACCEL_FLAGS[@]}" \
        -m 256M \
        -kernel "${KERNEL_IMG}" \
        -serial stdio \
        -display none \
        -no-reboot \
        -no-shutdown \
        -s \
        -S &          # -S: start paused; -s: GDB stub on port 1234
    QEMU_PID=$!
    echo "[debug-qemu] QEMU PID: ${QEMU_PID}"
    sleep 0.5         # give QEMU time to open the GDB port
fi

# ---------------------------------------------------------------------------
# Write a GDB init script to a temp file
# ---------------------------------------------------------------------------
GDB_INIT=$(mktemp /tmp/neomach-gdb-init.XXXXXX)
cat > "${GDB_INIT}" << EOF
# NEOMACH GDB init script — generated by tools/debug-qemu.sh

# Load kernel symbols from the ELF file.
# This gives GDB full source-level debugging information for the kernel.
file ${KERNEL_IMG}

# Connect to the QEMU GDB stub.
# 'target remote' uses the RSP (Remote Serial Protocol) over TCP.
target remote localhost:1234

# Useful default breakpoints for kernel bring-up:
# break kernel_main       # stop at C entry point
# break ipc_init          # stop when IPC subsystem initialises

echo \\n[GDB] Connected to QEMU stub on localhost:1234\\n
echo [GDB] Type 'continue' (or 'c') to begin execution.\\n
echo [GDB] Useful commands:\\n
echo   layout src      -- source + asm split view\\n
echo   break <func>    -- set a breakpoint\\n
echo   info registers  -- dump all registers\\n
echo   x/10i \$rip      -- disassemble 10 instructions at RIP\\n
echo \\n

EOF
trap "rm -f ${GDB_INIT}" EXIT

# ---------------------------------------------------------------------------
# Launch GDB
# ---------------------------------------------------------------------------
echo "[debug-qemu] Launching GDB ..."

# Prefer gdb-multiarch (supports x86-64 ELF on non-x86 hosts), then x86_64-elf-gdb,
# then plain gdb.
GDB_BIN=""
for candidate in gdb-multiarch x86_64-elf-gdb gdb; do
    if command -v "$candidate" &>/dev/null; then
        GDB_BIN="$candidate"
        break
    fi
done

if [[ -z "$GDB_BIN" ]]; then
    echo "[debug-qemu] ERROR: no GDB found. Install gdb-multiarch or x86_64-elf-gdb." >&2
    exit 1
fi

echo "[debug-qemu] Using GDB: $(command -v ${GDB_BIN})"
exec "${GDB_BIN}" -q -x "${GDB_INIT}"
